### ISSUE TITLE
`fetch` fails on windows

### ISSUE THREAD

**Issue by nektro** [nektro/zigmod#24]
blocked on https://github.com/ziglang/zig/issues/6364

**Comment by nektro** [comment]
With the addition of various workarounds https://github.com/nektro/zigmod/releases/tag/v66 + should now work for most workloads.

**Comment by nbness2** [comment]
`fetch` is still failing for me on Windows when trying to build zigmod from source following the instructions on the readme. Fails on loading `libyaml` every time.

**Comment by nektro** [comment]
https://clbin.com/iyNjH web viewable link

**Comment by kacogg5** [comment]
I'm having a similar issue on r84. No stack trace returned, only message was 'git fetch failed' trying to fetch capy-ui. Tried running as admin, no difference.
